version: "3.2"

networks:
  web-net:

services:
  app:
    container_name: app
    build: ./app
    entrypoint: /bin/sh
    stdin_open: true
    tty: true
    volumes: 
      - "./app:/usr/src/app"
    ports:
      - "5001:5001"
    restart: always

  web:
    container_name: web
    build: ./web
    volumes: 
      - "./web:/app"
    ports:
      - "5000:5000"
    restart: always
    networks:
        - web-net